server:
  servlet:
    contextPath: /dev
  port: 8888

spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: sa
  sql:
    init:
      mode: always
  jpa:
     database-platform: org.hibernate.dialect.H2Dialect
  h2:
     console:
        enabled: true
  servlet:
     multipart:
        max-file-size: 1024KB
        max-request-size: 1024KB
  http:
     multipart:
        enabled: true

  kafka:
     consumer:
        bootstrap-servers: "localhost:9092"
        group-id: "1212"
        auto-offset-reset: latest
        key-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
        value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
        properties:
         spring.json.value.default.type: sl.ms.inventorymanagement.dto.Student
         spring.deserializer.key.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
         "[spring.deserializer.value.delegate.class]": "org.springframework.kafka.support.serializer.JsonDeserializer"
     producer:
        bootstrap-servers: "localhost:9092"
        key-serializer: org.apache.kafka.common.serialization.StringSerializer
        value-serializer: org.springframework.kafka.support.serializer.JsonSerializer