/*CREATE SEQUENCE inventory_seq
START WITH 1
INCREMENT BY 1
CYCLE;

CREATE SEQUENCE product_seq
START WITH 1
INCREMENT BY 1
CYCLE;

INSERT INTO USERS (ID,USERNAME,PASSWORD) VALUES (1,
   'mani','$2a$10$alq80J4wtdc4tn0IiXHlD.N6vK9nzq.I.q5Zfjd560kNafJnemxBm');

INSERT INTO USERS (ID,USERNAME,PASSWORD) VALUES (2,
   'kandan','$2a$10$6wqBs5t8nqGpsjqOyP02iuW.D056pjPqG4cU6sefhZ7My0834x0DG'); */